### ISSUE TITLE
Don't require root for installation

### ISSUE THREAD

**Issue by jottr** [raitonoberu/sptlrx#3]
Please refrain from using `$ curl -sSL instl.sh/raitonoberu/sptlrx/macos | sudo bash`. 
This is considered [bad practice](https://tserong.github.io/sudo-wget/) and deemed unsafe.

Why does your script require `root` in the first place?

**Comment by raitonoberu** [comment]
I use [instl](https://github.com/installer/instl) to provide an automatic installation. This requires `root` because it puts the executable file in `/usr/local/bin`.

**I am aware of the fact that this is a bad practice**, so the user has the option to download it and install it manually. This will be removed from the README as soon as the package is available in the main repositories (already in AUR).

**Comment by HadetTheUndying** [comment]
Placing the file in `~/.local/bin` is probably a better idea and then recommending users add that to their $PATH. Your README.md doesn't have any build instructions so most people will default to just using `curl` to pull the prebuilt binary, better safe than sorry.
